# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Projects/FPGA/Sparring_Wario_Game/Sparring_Wario/Sparring_Wario.srcs/sources_1/ip/rom1/rom1.xci
# IP: The module: 'rom1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/FPGA/Sparring_Wario_Game/Sparring_Wario/Sparring_Wario.gen/sources_1/ip/rom1/rom1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Projects/FPGA/Sparring_Wario_Game/Sparring_Wario/Sparring_Wario.srcs/sources_1/ip/rom1/rom1.xci
# IP: The module: 'rom1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/FPGA/Sparring_Wario_Game/Sparring_Wario/Sparring_Wario.gen/sources_1/ip/rom1/rom1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
