# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/Projects/FPGA/Sparring_Wario_Game/Sparring_Wario/.Xil/Vivado-29256-DESKTOP-88C58FM/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7s50csga324-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/ip/hdmi_tx_0
    E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/ip/rom1
    E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/ip/clk_wiz_0
    e:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/ip/sound_rom
  } {
      C:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_vhdl -lib xil_defaultlib {
      E:/Projects/FPGA/Sparring_Wario_Game/Sparring_Wario/.Xil/Vivado-29256-DESKTOP-88C58FM/realtime/hdmi_tx_0_stub.vhdl
      E:/Projects/FPGA/Sparring_Wario_Game/Sparring_Wario/.Xil/Vivado-29256-DESKTOP-88C58FM/realtime/rom1_stub.vhdl
      E:/Projects/FPGA/Sparring_Wario_Game/Sparring_Wario/.Xil/Vivado-29256-DESKTOP-88C58FM/realtime/clk_wiz_0_stub.vhdl
      E:/Projects/FPGA/Sparring_Wario_Game/Sparring_Wario/.Xil/Vivado-29256-DESKTOP-88C58FM/realtime/sound_rom_stub.vhdl
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/new/CHAR_GEN.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/new/MY_PIXEL_DRIVER.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/new/clk_divide_125Hz.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/new/debouncer.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/new/audio_playback.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/imports/new/package_links.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/imports/new/package_ball.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/imports/new/package_ball_pink.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/imports/new/package_ball_red.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/imports/new/package_ball_punch_1.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/imports/new/package_ball_punch_2.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/imports/new/package_ball_punch_3.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/new/chain_bram.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/new/draw_background.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/new/draw_chain.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/new/draw_wario.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/imports/new/package_end_pos_1.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/imports/new/package_end_pos_2.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/imports/new/package_fall.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/imports/new/package_idle_1.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/imports/new/package_idle_2.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/imports/new/package_jump_1.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/imports/new/package_jump_2.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/imports/new/package_punch.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/imports/new/package_roll.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/new/sprite_bram.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/new/vga_controller_640_60.vhd
      E:/Projects/FPGA/Sparring_Wario/Sparring_Wario.srcs/sources_1/new/VGA_To_HDMI.vhd
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top VGA_To_HDMI
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "E:/Projects/FPGA/Sparring_Wario_Game/Sparring_Wario/.Xil/Vivado-29256-DESKTOP-88C58FM/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
